matches:
  - trigger: ".volt"
    replace: "Voltaren Arthritis Pain 1 % topical gel"
  - trigger: ".vsig"
    replace: "AAA (2-3 grams) 3-4x day prn pain"
  - trigger: ".tiz"
    replace: "Rx Tizanidine 4mg oral tablet"
  - trigger: ".tsig"
    replace: "Take 1-2 tabs QHS prn muscle spasms"
  - trigger: ".rob"
    replace: "Methocarbamol 500mg oral tablet"
  - trigger: ".rsig"
    replace: "Take 1 tab BID prn muscle spasms"
